name: Linux build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja Multi-Config

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential git make libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev && export CMAKE_C_COMPILER=gcc && export CMAKE_CXX_COMPILER=g++

      - name: Echo GCC version
        run: echo $(gcc --version)

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -G "${{env.CMAKE_GENERATOR}}"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Assets
        run: cd ${{github.workspace}}/build && sh ../data.sh

      - name: Stage files for artifact
        run: |
          mkdir -p ${{github.workspace}}/artifact-staging
          cp ${{github.workspace}}/build/${{env.BUILD_TYPE}}/exengine ${{github.workspace}}/artifact-staging/
          cp ${{github.workspace}}/build/data.ex ${{github.workspace}}/artifact-staging/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exengine-linux-build
          path: artifact-staging/